### ISSUE TITLE
Public function removal in minor version

### ISSUE THREAD

**Issue by k-cross** [elixir-ecto/ecto_sql#114]
Why was this function removed in a minor version?

https://github.com/elixir-ecto/ecto_sql/blob/v3.1.1/lib/mix/ecto_sql.ex#L8

**Comment by josevalim** [comment]
@k-cross that whole module and all functions in it are private: https://github.com/elixir-ecto/ecto_sql/blob/v3.1.1/lib/mix/ecto_sql.ex#L2

Therefore, we can remove the functions in it at any time. :) In this particular case, it was removed because we know provide an actually public implementation of it. See Ecto.Migrator.with_repo!

**Comment by k-cross** [comment]
Thank you for clearing that up, that helps!
