### ISSUE TITLE
Support for sub-directories (#68) changed migration execution order, breaking some use cases.

### ISSUE THREAD

**Issue by adrianomitre** [elixir-ecto/ecto_sql#170]
### Environment

* Elixir version (elixir -v): `Elixir 1.8.2 (compiled with Erlang/OTP 22)`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
* Ecto version (mix deps): `ecto_sql 3.2.2` & `ecto 3.2.5`
* Database adapter and version (mix deps): `postgrex 0.15.1`
* Operating system: Ubuntu 18.04.3 LTS (Bionic Beaver) (`Linux 4.15.0-70-generic #79-Ubuntu SMP`)

### Current behavior

Migration execution order:
```
20180409_add_some_field.exs
20180321174820_remove_some_table.exs
20180417144230_update_some_table.exs
```
### Expected behavior

Migration execution order:
```
20180321174820_remove_some_table.exs
20180409_add_some_field.exs
20180417144230_update_some_table.exs
```

### Discussion

Ecto v3.0.4 changed migration execution order and broke some use cases. The PR that did it was #68.

Contrast the following implementation from [v3.0.4](https://github.com/elixir-ecto/ecto_sql/blob/f56faae85f8d91b2932458b86f9543e7b5ae05ca/lib/ecto/migrator.ex#L546) 
```elixir
  defp migrations_for(migration_source) when is_binary(migration_source) do
    Path.join([migration_source, "**", "*.exs"])
    |> Path.wildcard()
    |> Enum.map(&extract_migration_info/1)
    |> Enum.filter(& &1)
    |> Enum.sort()
  end
```
with the [prior one](https://github.com/elixir-ecto/ecto/blob/4812550c60c26223742764d1b213e38d5eee1dd1/lib/ecto/migrator.ex#L227)
```elixir
  defp migrations_for(migration_source) when is_binary(migration_source) do
    query = Path.join(migration_source, "*")

    for entry <- Path.wildcard(query),
        info = extract_migration_info(entry),
        do: info
  end
```

### Proposed Solution

I believe that either (i) the original lexicographical ordering should be brought back, which to me makes sense considering the prefix means date times, or (ii) the breaking change should be clearly documented with suggested workarounds to restore previous behavior.

It is worth noting that proposed solution (i) is not expected to break migrations created with `mix ecto.gen.migration`, given their lexicographical and numerical ordering coincide.

**Comment by josevalim** [comment]
Hi @adrianomitre!

You are correct there was a change in behaviour, apologies. The first part of the migration was always meant to be treated as an integer, this is because you can also manually name your migrations as `1_`, `2_`, and so on. Which obviously means `10_` must come after. So in my mind, the change of behaviour fits more under of a bug fix.

However, since most Ecto installs out there use the current timestamp, which works both as numerical and lexicographical, it meant that we got the desired behaviour even without sorting.

We could reverse the behaviour but I am afraid that, by doing so, we are going to introduce yet another breaking change. And given that I consider the current behaviour to be the correct one, I am even less inclined to do such change.

If you want to send a PR that allows you explicitly opts-in into the lexicographical behaviour, we would gladly review and merge it. But perhaps the best option for you is to collapse your out of order migrations, by moving `20180409_add_some_field.exs` either at the end of the previous migration or at the beginning of the next migration. This means the behaviour will be the same across all versions and you won't re-run them in prod.

Thanks for the report!
