### ISSUE TITLE
Add missing features to MSSQL migrations (or raise if they are not supported)

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto_sql#202]
* [x] Add if not exists and remove if not exists to MSSQL: 57b97e8219a0f4dd33ba2509a63d499429f46dde
* [x] Add typed remove: 1354185c107e272e83511ab672b562bd08d9848f
* [x] Support prefix option in references: b4031ca619a13e1efdfb3ee64bd156bc9f51a1e6
* [x] Support drop_if_exists for Ecto.Migration.Constraints: 7eea8b75cb6971a9fabc1f359a3ebe8f34e3ebaf
* [x] Support :from in modify: https://github.com/elixir-ecto/ecto/commit/4e6e4932318285267567a584e2057a37f96b84c8

**Comment by josevalim** [comment]
I can help with some of those but others require a deeper knowledge of MSSQL which I probably won't be able to help with. :)

**Comment by josevalim** [comment]
I tackled one of them. :) Once we are done, we should probably [copy this test](https://github.com/elixir-ecto/ecto_sql/blob/master/test/ecto/adapters/myxql_test.exs#L1177-L1219) to TDS suite, replacing the current one with the same name, as it will cover all the necessary scenarios.

**Comment by mjaric** [comment]
@jose why query bind floats are converted to decimals by ecto?

example is
```elixir
TestRepo.all(from u in Usec, select: datetime_add(u.naive_datetime_usec, ^1500.0, "microsecond"))
```

`^1500.0 is converted to `#Decimal<1500.0>`. I know that float will lose precision in some cases but should user decide if value should be float or decimal?

**Comment by josevalim** [comment]
I think in this case it is decimal_add that says it expects a decimal? I don’t think we generally convert floats to decimals.

**Comment by mjaric** [comment]
Hi @josevalim, 

Regarding "Support :from in modify". Migration that you referenced in comment tries to modify primary key 

```elixir
  defmodule AlterColumnFromMigration do
    use Ecto.Migration

    def change do
      create table(:modify_from_authors, primary_key: false) do
        add :id, :integer, primary_key: true
      end
      # ..... other changes
      alter table(:modify_from_authors) do
        modify :id, :bigint, from: :integer
      end
      # ...... other changes
    end
  end
```

While other things works I still can't support `modify :id, :bigint, from: :integer`, nor SQL Server will. Error that SQL returns is 

`Line 1 (Error 4922): ALTER TABLE ALTER COLUMN id failed because one or more objects access this column.`

Reason is that Primary Key also is CONSTRAINT that must be removed in migration. BUT`modify` only tells that it want to modify column type only! Adapter can't conclude that column is Primary Key in this case, so we have to add `primary_key: true` in `opts[:from]` and in modify so PK constraint can be returned after column type change. I don't see this as and option so I could change this in PR if you don't mind. I will check MyXql and PG adapters for this change too and change adapters if required and ok by you.

Now, having in mind above. This is also the case with `serial` and `bigserial` types that are MSSQL's `INT IDENTITY(seed, inc)` and BIGINT IDENTITY(seed, inc)` and there is a catch :)  regardless if this column is PK or non PK we need to reseed last known SEED value. There is exclusion tag `:alter_primary_key` I used in `test_helper.exs` that skips tests doing this kind of migration. 

Reason is this: So far, when I manually did such tasks I used `DBCC` command in SQL to reach that value, but it prints that value in TDS Info token that is not exposed to result so ecto adapter can't reach it. I will check later if there is system table where this value is kept. Such table probably exists but question is " is it exposed to DB user/admin" 

I'll get back to last paragraph if I find that system table :)

**Comment by josevalim** [comment]
Sounds good. We just need to raise then if we see the `:from` option set. :)

**Comment by mjaric** [comment]
raise if serial is the type in modify/3 and there is no system table that can provide seed value?

**Comment by josevalim** [comment]
Oh, I misunderstood. I think for now we don't need to worry about the primary key scenario. I will add a note to the docs that `:from` cannot be used to modify primary keys, as there are usually a bunch of metadata attached to it.

Other than that, assuming that `:from` can be trivially implemented for MSSQL, then let's go ahead. Otherwise we can raise in MSSQL if `:from` is used.

**Comment by mjaric** [comment]
let me just step back and see if I should raise on modify completly, since DEFAULT constraints must be removed before column is altered. This means that I may add more exclusions in migrations :(

**Comment by josevalim** [comment]
To be fair, we may have the same issue with default in other databases, it is not super clear.

**Comment by mjaric** [comment]
There is one odd test case in (migrations)[https://github.com/elixir-ecto/ecto_sql/blob/ebd63dfd7ff7741aa4be2f32925672408691007d/integration_test/sql/migration.exs#L61]. 
 
Should this `default: nil` be interpreted as DEFAULT value is NULL or as remove default constraint?

**Comment by mjaric** [comment]
Ignore previous, no constraint is same as DEFAULT(NULL)

**Comment by mjaric** [comment]
ok, after some redo I added support for modify from, but we need to extend set of constraints to cover primary keys. Only drop and add constraint for now. Tho, it is always possible to execute custom query in migration :).

Here is how it is done in MSSQL 

add constraint
```tsql
ALTER TABLE [posts] ADD CONSTRAINT [posts_id_pkey] PRIMARY KEY (id);
```

drop constraint
```tsql
ALTER TABLE [posts] DROP CONSTRAINT [posts_id_pkey];
```

it is always possible to prefix drop with if statement in query (or in sql server 2017+ there is `DROP CONSTRAINT IF EXISTS`)

```tsql
IF (OBJECT_ID(N'[posts_id_pkey]', 'PK') IS NOT NULL) 
    ALTER TABLE [posts] DROP CONSTRAINT [posts_id_pkey];
```
or shorter in 2017+
```tsql
ALTER TABLE [posts] DROP CONSTRAINT IF EXISTS [posts_id_pkey];
```

@josevalim, should I leave this to custom script execute or to add PK constraint in `Ecto.Migration.Constraint` struct attribute `primary_key: nil | atom | String.t`  ?

**Comment by josevalim** [comment]
@mjaric I don't think we need to worry about primary key support for now. Other adapters don't support it either and nobody ever asked for it, so I am glad to punt it until we actually need to support it. :)

**Comment by josevalim** [comment]
Actually, it seems it works on other adapters. But for now, I would probably prefer to change the tests. I will merge your PR and we can continue from there. :)
