### ISSUE TITLE
Documentation of `Migration.execute/1`

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-ecto/ecto_sql#257]
I've just had a look at `Migration.execute/1`, and there seems to not be much explanation around the keyword list and anonymous function based functionality. I had questions like:

- What are the available keywords for the keyword list option?
- Where does the `repo()` call come from?

Would be great if those things could be amended.

**Comment by josevalim** [comment]
1. Keyword lists exists for non-SQL adapters, so it is not used in most cases.

2. `repo()` is a function defined in `Ecto.Migration`.

3. The anonymous function behaviour is for building complex reversible instructions where we execute the content of the function instead of the given SQL.

Can you please send a PR if all is clear now? :)

**Comment by LostKobrakai** [comment]
Great. Will try to put that into documentation form this evening.
