### ISSUE TITLE
Sandbox adapter does not follow Adpaters behaviour specs

### ISSUE THREAD

**Issue by jeanparpaillon** [elixir-ecto/ecto_sql#300]
### Current behavior

When using `Ecto.Adapters.SQL.Sandbox` pool, various functions expects adapters' `meta` to contain a `opts` key.
`Adapters` behaviour does not impose such key on meta.

In particular, `Sandbox` crashes with `ecto3_mnesia` adapter: see https://gitlab.com/patatoid/ecto3_mnesia/-/blob/master/lib/ecto/adapters/mnesia.ex#L117

### Expected behavior

`Sandbox` adapter should either:
* warn/log when `opts` key is not present
* use default opts whenever possible

Alternative:
* update `Ecto.Adapters.init/{0,1}`  callback typespec to include mandatory `opts` key

**Comment by josevalim** [comment]
The sandbox is only meant to work with the SQL adapters that explicitly `use Ecto.Adapters.SQL`. If the goal is to implement the sandbox for other adapters, it makes most sense to build a specific sandbox to them, especially because this is mostly a layer on top of DBConnection.OwnershipPool. Thanks!

**Comment by jeanparpaillon** [comment]
Ok, thanks for the clarification
