### ISSUE TITLE
Suggestion: mix task for squashing migrations

### ISSUE THREAD

**Issue by staring-frog** [elixir-ecto/ecto_sql#333]
Hi, on squashing migrations again :D
Current approach with `mix ecto.dump` + `mix ecto.load` doesn't fit well with Elixir releases: there's no mix binary in release to run the load task.
I think more convenient approach would be to squash a bunch of migrations into a sql file with a single migration to load it using existing `load_structure/2`. Newly created migration would have the ID of the latest migration squashed. That way release could run migrations as usual without conflicts either on new or existing deploys (only if it had that latest squashed migration applied though).
I could take a shot at making a PR with this kind of mix task. Do you like the idea?

**Comment by josevalim** [comment]
To be clear, the goal of mix ecto.dump+mix ecto.load was never to squash migrations, but more as a performance mechanism so you are not running migrations all the time. Especially between dev/tests.

In any case, it shouldn't matter for releases: you should never really run ecto.dump and ecto.load in production. And if you are squashing, you definitely want to squash migrations you already ran in production. Otherwise you can end-up squashing a mix of prod migrations with non-prod migrations, and that will cause failure.

So my suggestion for now is to play with squashing migrations as a separate package, to try the different approaches out, and maybe we can revisit if it is part of EctoSQL in the future. :) Thanks!

**Comment by staring-frog** [comment]
I see, thanks.
