### ISSUE TITLE
Postgres - Use pg_advisory_lock for locking migrations?

### ISSUE THREAD

**Issue by dbernheisel** [elixir-ecto/ecto_sql#365]
### Precheck

Discussion started here: https://github.com/fly-apps/safe-ecto-migrations/issues/2
Mailing List discussion here: https://groups.google.com/g/elixir-ecto/c/7jbjMA-dh0Y

In the discussions above, sounds like we're good to offer using `pg_advisory_lock` as an option.

### Environment

* Elixir version (elixir -v): 1.13
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 13
* Ecto version (mix deps): 3.7.1
* Database adapter and version (mix deps):
* Operating system: MacOS Big Sur 11.6

### Current behavior

Currently, the PG adapter will lock the `schema_migrations` table using and `LOCK` and leverages a database transaction to release that lock. https://github.com/elixir-ecto/ecto_sql/blob/v3.7.1/lib/ecto/adapters/postgres.ex#L215-L223

Since it requires the database transaction to release that lock, it implies that using some concurrent operations that cannot work inside of transactions (such as adding indexes concurrently) cannot be safely run without also removing the guarantee that multiple nodes won't run migrations at the same time. This would require the user to setup advisory locks manually to keep the guarantee.

### Expected behavior

Could we change to using `pg_advisory_lock` and `pg_advisory_unlock` for managing locks? That would allow database transactions to not be coupled with ensuring one node is running migrations.

Looks like `pg_advisory_lock` was introduced in Postgres 8.2 (2006-12-05) https://www.postgresql.org/docs/8.2/functions-admin.html

**Comment by josevalim** [comment]
A PR is welcome! We can keep the current mechanism just in case we run into pitfalls.

**Comment by wojtekmach** [comment]
in the linked issue @lowski mentioned one:

> > I feel like advisory lock could even be the default for PG, are there any downsides?

> I initially asked this because that's what Rails uses by default (at least for Postgres). The only downside I see is when someone is using PGBouncer in transaction pooling mode - it doesn't support advisory locks.

so unfortunately it likely cannot be a default, needs to be opt-in.

**Comment by greg-rychlewski** [comment]
It should be fine to use transaction-level advisory locks with PGBouncer in transaction pooling mode. i.e. `pg_advisory_xact_lock` instead of `pg_advisory_lock `. 

These behave like regular locks and are removed once the transaction is over instead of persisting until the session is killed or `pg_advisory_unlock` is called. If I'm understanding the ecto_sql code correctly, you are only holding the lock for a single transaction and not needing it at the session level. 

The reason session level advisory locks are not compatible with pgbouncer's transaction pooling mode is because one pgbouncer session can be routed to multiple different postgres backends over its lifetime. So if it's not guaranteed to be routed to the one with the session-level advisory lock it needs. 

References:
  - https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS
  - https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADVISORY-LOCKS

**Comment by warmwaffles** [comment]
> so unfortunately it likely cannot be a default, needs to be opt-in.

Yes it will need to be, as we can not utilize that locking mechanism in SQLite3. I would assume this holds true for mysql.

**Comment by dbernheisel** [comment]
> > so unfortunately it likely cannot be a default, needs to be opt-in.
> 
> 
> 
> Yes it will need to be, as we can not utilize that locking mechanism in SQLite3. I would assume this holds true for mysql.

This would only be applicable for Postgres adapter, so no worries about mysql or sqlite3 or mssql.

**Comment by greg-rychlewski** [comment]
Are you considering taking out the advisory lock before looking for pending migrations and then releasing it once all of them have completed? 

I just started looking over the code base so not sure what kind of chaos that would create, but it seems like it could have some nice benefits:

  - Not constantly having to re-check the completed migration versions
  - Not having other nodes attempting already completed migrations
