### ISSUE TITLE
Human readable UUID logs

### ISSUE THREAD

**Issue by tlvenn** [elixir-ecto/ecto_sql#368]
@pawurb opened a PR for this sometime ago, which unfortunately did not end up getting merged due to the approach taken but the issue / pain is real ;)

### Current behavior
Ecto.UUID values are currently logged at binary ids with is completely unreadable and makes working with UUIDs pretty painful.
![image](https://user-images.githubusercontent.com/3340262/146825628-e7a4dca6-1733-4d5d-b578-2523f2fc02fe.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/3340262/146825664-0a5ea843-6c53-4620-b503-1e7d1300b901.png)

For context: https://github.com/elixir-ecto/ecto_sql/pull/292 & https://github.com/elixir-ecto/ecto/pull/3531

**Comment by josevalim** [comment]
As mentioned in the issue, there needs to be some mechanism to annotate the log how to format types. Preferably in a way where don’t end up encoding the data again. We don’t have bandwidth to explore solutions, so unless someone devises an approach, we will likely end up closing this. :) thanks!

**Comment by josevalim** [comment]
I have one idea. In the Ecto.Query.Planner we traverse the query casting parameters. We could both cast parameters and keep the original parameters as is. We would pass the original parameters as an option to the adapter, something like :log_params, which we then use for querying.

**Comment by tlvenn** [comment]
Thanks a lot for the proposal @josevalim, I want to say I can take this but the planer is a pretty challenging beast on its own and I am not that familiar with the code base. If nobody else volunteer to do that part, I can try to dig into it but I would need some guidance please. Thanks !

**Comment by josevalim** [comment]
Yes, the planner is actually the most complex part of the codebase but I think you keep most of your changes small. In particular, you are only worried about the `plan` operation, as that handles in params. This code is responsible for handling params:

https://github.com/elixir-ecto/ecto/blob/b30e581e60662c307bfbc06c1970c3b519c31d48/lib/ecto/query/planner.ex#L736-L749

You can see that it is adding the current param `v` to the accumulator `acc`, I would change to something like this:

       case cast_param(kind, query, expr, v, type, adapter) do
          {:in, cast_v_and_v} -> {Enum.reverse(cast_v_and_v, acc), false}
          cast_v -> {[{cast_v, v} | acc], cacheable?}
        end

In other words, the goal is to keep all `values` and their cast versions. This implies a couple things:

1. You will have to change whatever returns `{:in, _}` to keep both `v` and `cast_v`

2. The [return of `plan_cache`](https://github.com/elixir-ecto/ecto/blob/b30e581e60662c307bfbc06c1970c3b519c31d48/lib/ecto/query/planner.ex#L628) (the thing that returns all params that you collect above), is now inaccurate. It returns a list of tuples instead of a list of values. You should change `plan_cache` to call `Enum.unzip`, so you get both `params` and `original_params` (i.e. `cast_v` and `v`), and return a four element tuple instead.

Doing the changes above will require changes in other parts of Ecto, but if you can do the above and make the suite pass (even if you don't use the `original_params` anywhere, it will be 95% of the job. The rest is easy and we can touch point later.

**Comment by greg-rychlewski** [comment]
I had an idea for this and was curious if the general approach is ok before finishing a PR. 

The idea is to have the adapter dumpers specify whether they want to keep the cast value for a type. This will wrap the value in a struct `%Ecto.Query.Param{cast: cast, dump: dump}` and then `cast` will be sent to the logger and `dump` to the driver. 

The upsides I see:
- not having to keep 2 copies of every param
- adapter creator has freedom to choose which types are better logged as cast. we don't have to worry about breaking anything by switching all types over to cast

The downsides I see:
- some extra work for the adapter creator if they want to take advantage of the improved logging. but i tried to keep it simple/easy
- have to loop through the params to extract the dumped value before sending to the driver, in case any of them are wrapped in the new struct

I have an implementation in my own branches to give a better idea of what I was thinking:

ecto_sql: https://github.com/greg-rychlewski/ecto_sql/commit/d666040bcdc51e854e86a4c82dae3a8b38873b81
ecto: https://github.com/greg-rychlewski/ecto/commit/18469aead4b7494823f90ea3c21160f063c9c24f

**Comment by josevalim** [comment]
Could we perhaps use the existing Tagged struct? I think adapters can already return it and they are passed forward.

**Comment by tlvenn** [comment]
Thanks a lot @greg-rychlewski for implementing this !

**Comment by greg-rychlewski** [comment]
No worries :). I still need to add it for `insert_all` and assigned myself this ticket incase you'd like to track the progress: https://github.com/elixir-ecto/ecto/issues/3933
