### ISSUE TITLE
CaseClauseError when starting sandbox with CockroachDB

### ISSUE THREAD

**Issue by davenguyen** [elixir-ecto/ecto_sql#473]
### Elixir version

Elixir 1.14.2 (compiled with Erlang/OTP 25)

### Database and Version

CockroachDB 22.2.2

### Ecto Versions

ecto 3.9.2, ecto_sql 3.9.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5

### Current behavior

Run `Sandbox.start_owner!(MyRepo, shared: not tags[:async])` with Cockroach DB.

Another was running `mix phx.gen.auth` and got the same error: https://elixirforum.com/t/ecto-and-cockroachdb/45684

### Expected behavior

Should start sandbox.

**Comment by davenguyen** [comment]
The issue seems to start here at `Ecto.Adapters.SQL.Sandbox.handle_begin/2`: https://github.com/elixir-ecto/ecto_sql/blob/83eddc0884cca84931e35c9a0c2229a90a8d4ed5/lib/ecto/adapters/sql/sandbox.ex#L335

This is calling `Postgrex.Protocol.handle_begin/2`: https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/protocol.ex#L497

The @spec here shows that `{DBConnection.status(), state}` is a valid return value. However, `Sandbox.handle_begin/2` does not handle that return value, only `{:ok, value, state}` or `{kind, err, state}`. I don't know enough to know how this should be handled instead.

**Comment by josevalim** [comment]
Can you please provide an example of how your repo is configured? The fact it returns :transaction seems to imply it is not really inside a transaction. :(

**Comment by davenguyen** [comment]
`config/config.exs`:
```
config :my_app,
  ecto_repos: [MyApp.Repo],
  generators: [binary_id: true],
  config_env: config_env(),
  sandbox: false
```

`config/test.exs`:
```
config :my_app, MyApp.Repo,
  username: "root",
  hostname: hostname,
  port: 26257,
  migration_lock: false,
  database: "my_app_test#{System.get_env("MIX_TEST_PARTITION")}",
  pool: Ecto.Adapters.SQL.Sandbox,
  pool_size: 10
```

**Comment by josevalim** [comment]
Yeah, I double checked and basically the person on the ElixirForum cannot start a transaction once the connection is checked out because the connection is already inside a transaction. I will push a commit to improve the error message but that won't make it work. Someone would need to investigate if this is an issue in Ecto or CockroachDB. I would try to reproduce the failure with PostgreSQL. If the failure does not happen with Postgres, then it is likely caused by CockroachDB not rolling back a transaction when it should.

**Comment by rafiss** [comment]
There is a difference between PostgreSQL and CockroachDB that may be relevant here.

CockroachDB errors if you execute BEGIN while inside of a transaction (so the transaction gets aborted):
```
root@localhost:26257/defaultdb> begin;
BEGIN

root@localhost:26257/defaultdb  OPEN> begin;
ERROR: there is already a transaction in progress
root@localhost:26257/? ERROR>
```

Whereas PostgreSQL simply shows a warning, but does not abort the transaction:
```
postgres=# begin;
BEGIN
postgres=*# begin;
WARNING:  there is already a transaction in progress
BEGIN
```

See https://github.com/cockroachdb/cockroach/issues/54954

**Comment by josevalim** [comment]
Thanks @rafiss! Postgrex tracks if you are inside the transaction or not and it should never emit a BEGIN if it is already in transaction, it always errors. So it aligns with CockroachDB.

**Comment by rafiss** [comment]
Is the same true when using the ROLLBACK TO SAVEPOINT command? I'm asking because I'd seen that come up in https://forum.cockroachlabs.com/t/elixir-ecto-and-cockroachdb-initial-setup/5131

**Comment by josevalim** [comment]
In theory yes: https://github.com/elixir-ecto/postgrex/blob/e77976ae2fb994004b7fe6cc176f62712e42284d/lib/postgrex/protocol.ex#L556-L569

We only rollback if we are inside a transaction but we don't check if the savepoint exists, I wonder if that could cause issues.

But this is all in theory. If you have a failing scenario you can reproduce, check the logs or wireshark to see what is being sent over the wire?

**Comment by davenguyen** [comment]
There is a wireshark capture in this thread here: https://forum.cockroachlabs.com/t/elixir-ecto-and-cockroachdb-initial-setup/5131

I'm not sure what versions this capture was made on.

**Comment by carldr** [comment]
This repository might be of use to anyone finding this issue and looking for a solution : https://github.com/btkostner/ecto_replay_sandbox

**Comment by rafiss** [comment]
Just a heads up: https://github.com/btkostner/ecto_replay_sandbox last was developed 4 years ago, and may be a bit out of date. It says "CockroachDB does not support nested transactions or savepoints," but CockroachDB has supported savepoints since v20.1: https://www.cockroachlabs.com/docs/releases/v20.1.html#v20-1-0-core-features

**Comment by rafiss** [comment]
> There is a wireshark capture in this thread here: [forum.cockroachlabs.com/t/elixir-ecto-and-cockroachdb-initial-setup/5131](https://forum.cockroachlabs.com/t/elixir-ecto-and-cockroachdb-initial-setup/5131)

I was able to look at the Wireshark captures from this forum issue. I diffed the CockroachDB and PostgreSQL captures side-by-side. Here are relevant snippets: 

<details>
<summary>CockroachDB</summary>

```
Frame 378: 294 bytes on wire (2352 bits), 294 bytes captured (2352 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 41892, Dst Port: 26257, Seq: 1949, Ack: 1227, Len: 226
PostgreSQL
    Type: Simple query
    Length: 29
    Query: SAVEPOINT postgrex_query
PostgreSQL
    Type: Bind
    Length: 147
    Portal: 
    Statement: ecto_insert_users_tokens_0
    Parameter formats: 5
        Format: Binary (1)
        Format: Binary (1)
        Format: Binary (1)
        Format: Binary (1)
        Format: Binary (1)
    Parameter values: 5
        Column length: 7
        Data: 73657373696f6e
        Column length: 32
        Data: 8851857d7f43c4e6241964cdbb1ee7e6c8cc042a0416fa0b77d587c22843ef07
        Column length: 16
        Data: 445652715fd346958aa52bb25be10d03
        Column length: 8
        Data: 00027b9bbbe64900
        Column length: 16
        Data: 98917a79f0a74857b56d491a0b570b16
    Result formats: 0
PostgreSQL
    Type: Execute
    Length: 9
    Portal: 
    Returns: all rows
PostgreSQL
    Type: Simple query
    Length: 37
    Query: RELEASE SAVEPOINT postgrex_query

    379 1.326195937    127.0.0.1             127.0.0.1             PGSQL    89     <C/Z

Frame 379: 89 bytes on wire (712 bits), 89 bytes captured (712 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 26257, Dst Port: 41892, Seq: 1227, Ack: 2175, Len: 21
PostgreSQL
    Type: Command completion
    Length: 14
    Tag: SAVEPOINT
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: In a transaction (84)

    380 1.327033360    127.0.0.1             127.0.0.1             PGSQL    383    <2/E

Frame 380: 383 bytes on wire (3064 bits), 383 bytes captured (3064 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 26257, Dst Port: 41892, Seq: 1248, Ack: 2175, Len: 315
PostgreSQL
    Type: Bind completion
    Length: 4
PostgreSQL
    Type: Error
    Length: 309
    Severity: ERROR
    Code: 23505
    Detail: Key (context,token)=('session','\x8851857d7f43c4e6241964cdbb1ee7e6c8cc042a0416fa0b77d587c22843ef07') already exists.
    Constraint: users_tokens_context_token_index
    File: errors.go
    Line: 126
    Routine: NewUniquenessConstraintViolationError
    Message: duplicate key value violates unique constraint "users_tokens_context_token_index"

    381 1.327046342    127.0.0.1             127.0.0.1             PGSQL    74     <Z

Frame 381: 74 bytes on wire (592 bits), 74 bytes captured (592 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 26257, Dst Port: 41892, Seq: 1563, Ack: 2175, Len: 6
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: In a failed transaction (69)

    383 1.327082430    127.0.0.1             127.0.0.1             PGSQL    148    >S/Q

Frame 383: 148 bytes on wire (1184 bits), 148 bytes captured (1184 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 41892, Dst Port: 26257, Seq: 2175, Ack: 1569, Len: 80
PostgreSQL
    Type: Sync
    Length: 4
PostgreSQL
    Type: Simple query
    Length: 74
    Query: ROLLBACK TO SAVEPOINT postgrex_query;RELEASE SAVEPOINT postgrex_query

    384 1.327120422    127.0.0.1             127.0.0.1             PGSQL    74     <Z

Frame 384: 74 bytes on wire (592 bits), 74 bytes captured (592 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 26257, Dst Port: 41892, Seq: 1569, Ack: 2255, Len: 6
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: In a failed transaction (69)

    385 1.327166970    127.0.0.1             127.0.0.1             PGSQL    101    <C/C/Z

Frame 385: 101 bytes on wire (808 bits), 101 bytes captured (808 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 26257, Dst Port: 41892, Seq: 1575, Ack: 2255, Len: 33
PostgreSQL
    Type: Command completion
    Length: 13
    Tag: ROLLBACK
PostgreSQL
    Type: Command completion
    Length: 12
    Tag: RELEASE
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: In a transaction (84)

    386 1.328137361    127.0.0.1             127.0.0.1             PGSQL    82     >Q

Frame 386: 82 bytes on wire (656 bits), 82 bytes captured (656 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 41892, Dst Port: 26257, Seq: 2255, Ack: 1608, Len: 14
PostgreSQL
    Type: Simple query
    Length: 13
    Query: ROLLBACK

    390 1.328831034    127.0.0.1             127.0.0.1             PGSQL    84     >

Frame 390: 84 bytes on wire (672 bits), 84 bytes captured (672 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 41894, Dst Port: 26257, Seq: 1, Ack: 1, Len: 16
PostgreSQL
    Type: Cancel request
    Length: 16
    PID: 0
    Key: 0
```
</details>

<details>
<summary>PostgreSQL</summary>

```
Frame 243: 294 bytes on wire (2352 bits), 294 bytes captured (2352 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 37926, Dst Port: 5432, Seq: 3489, Ack: 1880, Len: 226
PostgreSQL
    Type: Simple query
    Length: 29
    Query: SAVEPOINT postgrex_query
PostgreSQL
    Type: Bind
    Length: 147
    Portal: 
    Statement: ecto_insert_users_tokens_0
    Parameter formats: 5
        Format: Binary (1)
        Format: Binary (1)
        Format: Binary (1)
        Format: Binary (1)
        Format: Binary (1)
    Parameter values: 5
        Column length: 7
        Data: 73657373696f6e
        Column length: 32
        Data: b0d66530bb86a405daff166b8e62ed11757c7cce6cf41d3100e93f6a1895abaf
        Column length: 16
        Data: 3ce8c3e10e344ac8a536f62d77869d9f
        Column length: 8
        Data: 00027b9bbec2b500
        Column length: 16
        Data: 03f452513fef43e8bebd6d98be4ad401
    Result formats: 0
PostgreSQL
    Type: Execute
    Length: 9
    Portal: 
    Returns: all rows
PostgreSQL
    Type: Simple query
    Length: 37
    Query: RELEASE SAVEPOINT postgrex_query

    244 1.745868845    127.0.0.1             127.0.0.1             PGSQL    89     <C/Z

Frame 244: 89 bytes on wire (712 bits), 89 bytes captured (712 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 5432, Dst Port: 37926, Seq: 1880, Ack: 3715, Len: 21
PostgreSQL
    Type: Command completion
    Length: 14
    Tag: SAVEPOINT
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: In a transaction (84)

    245 1.745974728    127.0.0.1             127.0.0.1             PGSQL    391    <2/E

Frame 245: 391 bytes on wire (3128 bits), 391 bytes captured (3128 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 5432, Dst Port: 37926, Seq: 1901, Ack: 3715, Len: 323
PostgreSQL
    Type: Bind completion
    Length: 4
PostgreSQL
    Type: Error
    Length: 317
    Severity: ERROR
    Text: ERROR
    Code: 23505
    Message: duplicate key value violates unique constraint "users_tokens_context_token_index"
    Detail: Key (context, token)=(session, \xb0d66530bb86a405daff166b8e62ed11757c7cce6cf41d3100e93f6a1895abaf) already exists.
    Schema: public
    Table: users_tokens
    Constraint: users_tokens_context_token_index
    File: nbtinsert.c
    Line: 527
    Routine: _bt_check_unique

    247 1.746013716    127.0.0.1             127.0.0.1             PGSQL    148    >S/Q

Frame 247: 148 bytes on wire (1184 bits), 148 bytes captured (1184 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 37926, Dst Port: 5432, Seq: 3715, Ack: 2224, Len: 80
PostgreSQL
    Type: Sync
    Length: 4
PostgreSQL
    Type: Simple query
    Length: 74
    Query: ROLLBACK TO SAVEPOINT postgrex_query;RELEASE SAVEPOINT postgrex_query

    248 1.746027112    127.0.0.1             127.0.0.1             PGSQL    74     <Z

Frame 248: 74 bytes on wire (592 bits), 74 bytes captured (592 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 5432, Dst Port: 37926, Seq: 2224, Ack: 3795, Len: 6
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: In a failed transaction (69)

    249 1.746066426    127.0.0.1             127.0.0.1             PGSQL    101    <C/C/Z

Frame 249: 101 bytes on wire (808 bits), 101 bytes captured (808 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 5432, Dst Port: 37926, Seq: 2230, Ack: 3795, Len: 33
PostgreSQL
    Type: Command completion
    Length: 13
    Tag: ROLLBACK
PostgreSQL
    Type: Command completion
    Length: 12
    Tag: RELEASE
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: In a transaction (84)

    251 1.747221279    127.0.0.1             127.0.0.1             PGSQL    82     >Q

Frame 251: 82 bytes on wire (656 bits), 82 bytes captured (656 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 37926, Dst Port: 5432, Seq: 3795, Ack: 2263, Len: 14
PostgreSQL
    Type: Simple query
    Length: 13
    Query: ROLLBACK

    252 1.747269195    127.0.0.1             127.0.0.1             PGSQL    88     <C/Z

Frame 252: 88 bytes on wire (704 bits), 88 bytes captured (704 bits) on interface any, id 0
Linux cooked capture v1
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 5432, Dst Port: 37926, Seq: 2263, Ack: 3809, Len: 20
PostgreSQL
    Type: Command completion
    Length: 13
    Tag: ROLLBACK
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: Idle (73)
```

</details>

This shows that CockroachDB and PostgreSQL both are returning the same responses over pgwire. The difference comes at the end of these captures: after there is an error inserting a row, the driver sends `ROLLBACK TO SAVEPOINT postgrex_query;RELEASE SAVEPOINT postgrex_query`, and CockroachDB and PostgreSQL respond the same way. Then the driver sends `ROLLBACK`. In the Postgres capture, the database sends back a "ROLLBACK complete" message. But in the CockroachDB capture, the client sends a pgwire `cancel request` before the database responds to the ROLLBACK (presumably this is because Ecto experience the "no match of right hand side value" error).

It's not clear to me where there's a difference in CockroachDB that would explain the behavior. @davenguyen are you able to create Wireshark captures of your own for CockroachDB and PostgreSQL? Also, can you provide code that reproduces the issue? (I can investigate from the database-side, but I'm very new to Elixir/Ecto, so if there's a problem in the code, I will not be too helpful.)

**Comment by josevalim** [comment]
Amazing work @rafiss! Perhaps it is worth reporting a bug on CockroachDB? I would also be fine with a PR that supports a cancel request on ROLLBACK.

**Comment by rafiss** [comment]
I don't think that's the problem. I believe the cancel request is sent by Ecto _after_ it encounters the  "no match of right hand side value" error. So by the time the cancel request is sent, the bug, wherever it is, has already occurred. Also, CockroachDB does correctly handle the `cancel request` after the ROLLBACK, so that's not the issue.

There are two things to figure out:
- @davenguyen can you share your own Wireshark capture or code that reproduces the problem, so we can determine if you are hitting the same bug as the forum user.
- Assuming yes, then why does Ecto experience the "no match of right hand side value" error rather than waiting for the "rollback complete" message from CockroachDB.

**Comment by chargreezy** [comment]
I've also been experiencing this issue when running my test suite, i've been following this thread and looking into it. 

It certainly is happening in response to a failed transaction causing the subsequent checkout to fail. Unfortunately I can't seem to write a test to reliably trigger, even adding logging can can seem to change the outcome, which makes me think it's some sort of race condition that is triggering in response to the rollback command.

Reading the CockroachDB documentation and from my observations the savepoint rollback mechanic should work fine. I think the first set to debugging would be to write a reliably failing test.

**Comment by chargreezy** [comment]
Ok so I've been experiencing the same issue, I dug into this and did some additional wireshark debugging.

I believe the problem is cockroach is sending an additional `ReadyForQuery` after the transaction error. I attached some minimal wireshark dumps with the additional packets.

[postgresql](https://pastebin.com/hbkwxdNw)
[cockroachdb](https://pastebin.com/CfKaXN5W)

If we compare the wireshark dumps there is an additional `ReadyForQuery` (line 77) packet sent by cockroach after the constraint error is fired, this is unexpected by ecto. After the rollback is triggered instead of getting a `ReadyForQuery, CommandComplete` sequence we end up with `ReadyForQuery, ReadyForQuery` with the `CommandComplete` waiting to be read on the buffer. This leaves ecto in a broken transaction state so it errors out when it next tries to open a new transaction.

You can see the expected recv order [here](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/protocol.ex#L1724).

After reading through the wire documentation I think Cockroach is not supposed to send the `ReadyForQuery` after a `Bind` until they receive the `Sync` message, this is documented in [here](https://www.postgresql.org/docs/current/protocol-flow.html) in the Extended Query section. So this may be an issue on the Cockroach end.

We could potentially put a workaround in postgrex to read repeated `ReadyForQuery` messages but I'm unsure what the downstream effect would be. I've [tested](https://github.com/elixir-ecto/postgrex/commit/86ec11159d74b8b714fd8d53957225b66d5196da) adding an additional expectation in the protocol code and that seems to fix the test issues I was seeing, but I don't know how much I like the idea of `recv_ready(s)`.

**Comment by josevalim** [comment]
Great finding @chargreezy! Can you please report an issue upstream on Cockroach?

**Comment by rafiss** [comment]
Thanks @chargreezy! when you file the issue at https://github.com/cockroachdb/cockroach/issues/new/choose can you also include the capture of the pgwire messages sent from the client to the database, starting from the beginning of your test? That will make it easy for us to add a regression test.

**Comment by rafiss** [comment]
I've narrowed down a test case we can add to CRDB and filed an issue: https://github.com/cockroachdb/cockroach/issues/103936

**Comment by chargreezy** [comment]
Thanks @rafiss! The protocol documentation is a little confusing but I'm going to assume PostgeSQL has the correct implementation. In the meantime I've updated my branch with a quick fix that seems to keep functionality for both Postgres and CockroachDB.

**Comment by rafiss** [comment]
Hm there's a bit more nuance to how Postgres does error handling here than I realized. I left a comment at https://github.com/cockroachdb/cockroach/issues/103936#issuecomment-1564629008 and we can move more discussion there.

**Comment by josevalim** [comment]
Thank you @rafiss, @chargreezy, and everyone who helped address this! :heart:
